name: Sync Image to Aliyun Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Install Skopeo
      run: |
        sudo apt-get update
        sudo apt-get install -y skopeo

    - name: Login to Aliyun Docker Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-shanghai.aliyuncs.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        skopeo copy docker://docker.io/openjdk:21-jre-slim docker://registry.cn-shanghai.aliyuncs.com/bomou/openjdk:21-jre-slim

    - name: Debug Info
      run: |
        echo "Checking Docker version:"
        docker --version
        echo "Checking Skopeo version:"
        skopeo --version
